import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { Stack, useRouter } from 'expo-router';
import { colors } from '@/constants/colors';
import { ArrowLeft, Shield, Mail } from 'lucide-react-native';

export default function PrivacyPolicy() {
  const router = useRouter();
  
  return (
    <>
      <Stack.Screen 
        options={{ 
          title: 'Privacy Policy',
          headerLeft: () => (
            <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
              <ArrowLeft size={24} color={colors.primary} />
            </TouchableOpacity>
          ),
        }} 
      />
      
      <ScrollView style={styles.container} contentContainerStyle={styles.scrollContent}>
        <View style={styles.header}>
          <Shield size={48} color={colors.primary} />
          <Text style={styles.title}>Privacy Policy</Text>
          <Text style={styles.subtitle}>Padel Stats</Text>
          <Text style={styles.lastUpdated}>Last updated: July 20, 2025</Text>
        </View>
        
        <View style={styles.content}>
          <Text style={styles.introText}>
            Your privacy is very important to us. The Padel Stats app, developed by Karol Krawczyński, does not collect, store, or process any personal data from users.
          </Text>
          
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>1. Data Processing</Text>
            <Text style={styles.sectionText}>
              All data entered into or generated by the app is stored locally on the user's device. The app does not transmit any information to external servers or third-party services.
            </Text>
          </View>
          
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>2. Types of Data Processed</Text>
            <Text style={styles.sectionText}>
              The app only processes game-related statistics (e.g. number of points, errors, wins) to:
            </Text>
            <View style={styles.bulletPoints}>
              <Text style={styles.bulletPoint}>• present user performance statistics,</Text>
              <Text style={styles.bulletPoint}>• support progress tracking.</Text>
            </View>
            <Text style={styles.sectionText}>
              These data points do not contain any personally identifiable information (PII).
            </Text>
          </View>
          
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>3. Data Sharing</Text>
            <Text style={styles.sectionText}>
              The app does not share any data with third parties. It does not use advertising networks, analytics tools, or any login systems.
            </Text>
          </View>
          
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>4. User Rights</Text>
            <Text style={styles.sectionText}>
              Since the app does not collect personal data, there is no need for user consent, nor are any rights related to data access, correction, or deletion applicable in this context.
            </Text>
          </View>
          
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>5. Contact</Text>
            <Text style={styles.sectionText}>
              If you have any questions about this privacy policy or the app, you can contact us at:
            </Text>
            <TouchableOpacity style={styles.contactButton}>
              <Mail size={20} color={colors.primary} />
              <Text style={styles.contactEmail}>karol.krawczynski4@gmail.com</Text>
            </TouchableOpacity>
          </View>
        </View>
      </ScrollView>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  backButton: {
    padding: 8,
    marginLeft: -8,
  },
  header: {
    alignItems: 'center',
    padding: 24,
    backgroundColor: colors.card,
    marginBottom: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.text,
    marginTop: 16,
  },
  subtitle: {
    fontSize: 18,
    color: colors.primary,
    fontWeight: '600',
    marginTop: 4,
  },
  lastUpdated: {
    fontSize: 14,
    color: colors.textLight,
    marginTop: 8,
  },
  content: {
    padding: 20,
  },
  introText: {
    fontSize: 16,
    color: colors.text,
    lineHeight: 24,
    marginBottom: 24,
    fontWeight: '500',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 12,
  },
  sectionText: {
    fontSize: 16,
    color: colors.text,
    lineHeight: 24,
    marginBottom: 8,
  },
  bulletPoints: {
    marginLeft: 16,
    marginVertical: 8,
  },
  bulletPoint: {
    fontSize: 16,
    color: colors.text,
    lineHeight: 24,
    marginBottom: 4,
  },
  contactButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background,
    padding: 16,
    borderRadius: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  contactEmail: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: '600',
    marginLeft: 8,
  },
});